### ISSUE TITLE
Uid does not save

### ISSUE THREAD

**Issue by towboogie** [zpukr/esp8266-WindStation#1]
Great Project zpukr - my windgurustation2 stopped working, and for about $5 looks like i can get it back up and running!

Having an issue where the uid does not save during set up - error message is below

> 19:55:02.285 -> http://www.windguru.cz/upload/api.php?uid=&salt=795955&hash=6ecc5422c7c57fc0c24c24112ec98c84&wind_min=0.00&wind_avg=0.00&wind_max=0.00
> 19:55:03.013 -> ERROR (unknown station)

after saving the data the serial output shows that it has mounted the file system, and wifi password is saved.

> 08:18:35.314 -> ESP ChipID: 4559E2
> 08:18:35.349 -> mounting FS...
> 08:18:35.349 -> mounted file system
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: server
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: port
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: user
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: pass
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: kc_wind
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: windguru_uid
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.384 -> *WM: windguru_pass
> 08:18:35.384 -> *WM: Adding parameter
> 08:18:35.418 -> *WM: vaneMaxADC
> 08:18:35.418 -> *WM: Adding parameter
> 08:18:35.418 -> *WM: vaneOffset
> 

running on a nodemcu, and i have changed nothing in your code.  the UID is raglankitebeach, so nothing to special.

Any idea what could be causing this?

Update:

Using the chrome on windows seems to have solved the saving issue.

is there a simple way to calibrate?  Im using a davis anemometer which outputs 1600 pulses an hour for every 1mph in windspeed.

**Comment by zpukr** [comment]
Simplest way to calibrate - use MQTT control panel for real time viewing/setup variables. Below, I posted a ready-use template for the MQTT Dash application https://play.google.com/store/apps/details?id=net.routix.mqttdash&hl=uk

`[{"mainTextSize":"LARGE","postfix":" m/s","prefix":"","textColor":-192,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":1540661885,"intermediateStateTimeout":10,"jsOnReceive":"","jsonPath":"$.Avr","lastJsonPathValue":"5.62","lastPayload":"{\"Min\": 1.80, \"Avr\": 5.62, \"Max\": 9.90, \"Dir\": 297}","qos":0,"retained":false,"topic":"windpoint/wind","topicPub":"windpoint","updateLastPayloadOnPub":false,"id":"9b0b155b-29c1-48fa-9085-7c54b0f73bbe","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661855,"longId":5,"name":"WindAvr","type":1},{"decimalPrecision":0,"displayPayloadValue":true,"maxValue":360.0,"minValue":0.0,"postfix":"°","prefix":"","progressColor":-192,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":1540661885,"intermediateStateTimeout":1,"jsOnReceive":"","jsonPath":"$.Dir","lastJsonPathValue":"297","lastPayload":"{\"Min\": 1.80, \"Avr\": 5.62, \"Max\": 9.90, \"Dir\": 297}","qos":1,"retained":false,"topic":"windpoint/wind","topicPub":"windpoint","updateLastPayloadOnPub":false,"id":"716bae44-f2f5-4ce7-9f79-61292c0d2f2f","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661855,"longId":13,"name":"Direction","type":3},{"mainTextSize":"MEDIUM","postfix":" m/s","prefix":"","textColor":-12550144,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"$.Min","lastJsonPathValue":"1.8","lastPayload":"{\"Min\": 1.80, \"Avr\": 5.62, \"Max\": 9.90, \"Dir\": 297}","qos":0,"retained":false,"topic":"windpoint/wind","topicPub":"sensor","updateLastPayloadOnPub":false,"id":"fd6e2415-bad0-404c-a43b-b164171b8017","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661855,"longId":4,"name":"WindMin","type":1},{"mainTextSize":"MEDIUM","postfix":" m/s","prefix":"","textColor":-65472,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"$.Max","lastJsonPathValue":"9.9","lastPayload":"{\"Min\": 1.80, \"Avr\": 5.62, \"Max\": 9.90, \"Dir\": 297}","qos":0,"retained":false,"topic":"windpoint/wind","topicPub":"sensor","updateLastPayloadOnPub":false,"id":"7eed0deb-cb11-4ec5-ab1f-9ce9305fb341","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661855,"longId":6,"name":"WindMax","type":1},{"mainTextSize":"LARGE","postfix":"°","prefix":"","textColor":-1,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"$.Temp","lastJsonPathValue":"10.0","lastPayload":"{\"Temp\": 10.00, \"Humidity\": 87.00}","qos":0,"retained":false,"topic":"windpoint/temp","topicPub":"sensor","updateLastPayloadOnPub":false,"id":"923e726b-7edd-40dd-ad5d-6831cd6670e0","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661854,"longId":1,"name":"Temperature","type":1},{"mainTextSize":"LARGE","postfix":"%","prefix":"","textColor":-1,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"$.Humidity","lastJsonPathValue":"87.0","lastPayload":"{\"Temp\": 10.00, \"Humidity\": 87.00}","qos":0,"retained":false,"topic":"windpoint/temp","topicPub":"","updateLastPayloadOnPub":true,"id":"4db3b3ca-d9d4-472f-af7c-f8ed3403a0a6","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661854,"longId":7,"name":"Humidity","type":1},{"decimalPrecision":0,"displayPayloadValue":true,"maxValue":140.0,"minValue":20.0,"postfix":"","prefix":"","progressColor":-1,"enableIntermediateState":false,"enablePub":true,"enteredIntermediateStateAt":1540661885,"intermediateStateTimeout":10,"jsOnReceive":"","jsonPath":"","lastPayload":"90","qos":1,"retained":false,"topic":"windpoint/kc_wind","topicPub":"windpoint","updateLastPayloadOnPub":false,"id":"4d50b3f6-8f21-40b9-b90b-17031b769896","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661809,"longId":8,"name":"kcWind","type":3},{"iconOff":"ic_cloud_download","iconOn":"ic_cloud_download","offColor":-1,"onColor":-1,"payloadOff":"sensor","payloadOn":"sensor","enableIntermediateState":true,"enablePub":true,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"","lastPayload":"sensor","qos":1,"retained":false,"topic":"windpoint","topicPub":"","updateLastPayloadOnPub":true,"id":"df5bfda3-d3b7-4c92-8fe7-a425e20cfd95","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661840,"longId":9,"name":"Update","type":2},{"mainTextSize":"SMALL","postfix":"","prefix":"","textColor":-1,"enableIntermediateState":true,"enablePub":false,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"","lastPayload":"ADC:781","qos":1,"retained":false,"topic":"windpoint/debug","topicPub":"","updateLastPayloadOnPub":true,"id":"d8222a02-352e-48d0-b466-b78e9a382a19","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661885,"longId":11,"name":"Debug","type":1},{"iconOff":"ic_explore","iconOn":"ic_explore","offColor":-1,"onColor":-1,"payloadOff":"adc","payloadOn":"adc","enableIntermediateState":false,"enablePub":true,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"","lastPayload":"adc","qos":1,"retained":false,"topic":"windpoint","topicPub":"","updateLastPayloadOnPub":true,"id":"cf88116a-4130-45bc-b77f-f6a0895b5548","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540661885,"longId":12,"name":"Read ADC","type":2},{"iconOff":"ic_flash_on","iconOn":"ic_flash_on","offColor":-1,"onColor":-1,"payloadOff":"reset","payloadOn":"reset","enableIntermediateState":true,"enablePub":true,"enteredIntermediateStateAt":0,"intermediateStateTimeout":0,"jsOnReceive":"","jsonPath":"","lastPayload":"reset","qos":1,"retained":false,"topic":"windpoint","topicPub":"","updateLastPayloadOnPub":true,"id":"aabe562f-5790-4d2a-ae3b-60526dfd4621","jsBlinkExpression":"","jsOnDisplay":"","jsOnTap":"","lastActivity":1540372437,"longId":10,"name":"Reset!","type":2}]`

**Comment by zpukr** [comment]
MQTT Dash screenshot:
![alt tag](https://raw.githubusercontent.com/zpukr/esp8266-WindStation/master/Screenshot_20190216.png)
