### ISSUE TITLE
Not wifi conection 

### ISSUE THREAD

**Issue by odnanref25** [zpukr/esp8266-WindStation#2]
Hi, first of all, thanks a lot for your project :)

I have compiled ".ino" in my esp8266 and I can't see "WindStationAP" wifi. I have all the libraries installed and the complilation goes well but when the compilation is finish i look for new wifi account with my mobile phone and nothing new.

This is my first Arduino project :P

**Comment by odnanref25** [comment]
Ok, I have solved this problem, I was using the wrong board!! For the Wemos D1 mini the right board seems to be "LOLIN (Wemos) D1 R2 & mini.

**Comment by zpukr** [comment]
The project is guaranteed to work on any ESP8266 ESP-12E / ESP-12F (wemos, witty cloud, nodemcu etc) board. But you must select the appropriate board in the settings of the Arduino IDE before flashing firmware of course. Or second way is use ready to flash firmware and utilities from "bin" folder
