### ISSUE TITLE
MQTT DASHBOARD

### ISSUE THREAD

**Issue by odnanref25** [zpukr/esp8266-WindStation#3]
Hi, Could you explain how to install MQTT Dashboard template? I'm looking into the app and I don't be able to install the template.

Thanks :)

**Comment by zpukr** [comment]
1. Create new empty Dash, at sample "WindStation". Enter MQTT server addr, port, password etc.
2. Open Dash, click "Import/Export", click "Subscribe and..."
https://github.com/zpukr/esp8266-WindStation/blob/master/Screenshot_20190304-204054.jpg
3. Send template to application fom WEB interface of yours MQTT server or another application to topic "mertic/exchange" at sample
