### ISSUE TITLE
Value for kc_wind?

### ISSUE THREAD

**Issue by brian-naylor** [zpukr/esp8266-WindStation#5]
Hello,
Thanks for sharing your code, which looks great and works well.
However, I am seeing very large wind readings, far above other readings locally.   What values are you using for the kc_wind to adjust its calibration for the Davis 6410?

eg.
windimpulse: 12 millis: 3001     7.82 knots
windimpulse:11 millis: 3001      7.17 knots
windimpulse: 9 millis: 3001      5.86  etc

**Comment by ricka75** [comment]
Hi, need to put 4.7k  resistor between power and wind speed to avoid misreadings. http://cactus.io/hookups/weather/anemometer/davis/hookup-arduino-to-davis-anemometer
https://www.youtube.com/watch?v=wxjerCHCEMg

**Comment by ricka75** [comment]
I would first check if pullup resistor needed between VCC and Pin. I had the same issue with abnormal readings.

**Comment by zpukr** [comment]
I don't know sharp value of kc_wind for you case. You can use any value from 1 to 999. If for kc_wind=1 wind still very large you can modife row: 
`windMS = (float) windimpulse * windPeriodSec*1000 /(millis() - secTTasks) *atoi(kc_wind)/100;`
to
`windMS = (float) windimpulse * windPeriodSec*1000 /(millis() - secTTasks) *atoi(kc_wind)/1000;`
